### ISSUE TITLE
Script will not exit when hotkey listener is used

### ISSUE THREAD

**Issue by Drayux** [StarrFox/wizwalker#20]
Forgive me if the source of this error appears to be a lack of experience on my end, I am very new to threaded operation--however it appears that whenever I call Listener.listen() the script becomes caught in some form of loop and even if I don't await, and call exit() next line, the script will not exit. Keyboard interrupt also has no impact. 

I've replicated the sample code shown in the docs, and placed the contents of the listen_for_a() function within the main function of my script (that is called in asyncio.run() ) and still run into this issue.

Let me know if you need further information or detail. :)

**Comment by StarrFox** [comment]
Hey drayux, what version of wizwalker do you have? and does the hotkey still work?

**Comment by Drayux** [comment]
Good question! It appears that I had 1.1.1, and in that version, yes, the hotkey worked, and the program would continue after pressing the hotkey, the only thing that seemed wrong was the failure to exit. 
Upon your mention of this, however, I updated to 1.2.7, and the hotkey no longer works in this version.

**Comment by StarrFox** [comment]
This issue should be fixed in https://github.com/StarrFox/wizwalker/commit/b401acbcc76a3ed8f9078b7f06bdbb775933d4d6 you just need to use .close on the listener
